### ISSUE TITLE
piper::pipe equivalent?

### ISSUE THREAD

**Issue by oblique** [smol-rs/async-channel#1]
I think `piper::pipe` is very useful when you need AsyncRead/AsyncWrite on just bytes.

Are you planing to move its implementation here?

**Comment by notgull** [comment]
It looks like the `pipe` implementation was [inlined into `blocking`](https://github.com/smol-rs/blocking/blob/dbdef7e55b5078615dae30141ed3b5db4724d00e/src/lib.rs#L917-L1264), although I'm not really sure why it isn't publicly exposed anywhere else. Maybe it's because the API is somewhat more obtuse?

@smol-rs/admins What would you think of extracting the `pipe` implementation in `blocking` into its own crate? [`async-pipe`](https://crates.io/crates/async-pipe) is already taken, so we would have to either come up with a new name or expose it in another crate (`futures_lite::io` may be a good place to put it).

**Comment by zseri** [comment]
Although I'd argue that the pipe implementation is strongly bounded in purpose to `blocking` itself, so just exporting it would imo be also ok (and less of a hassle)

**Comment by notgull** [comment]
It looks like the original repository for `piper` was lost, so I've created a new one [here](https://github.com/notgull/piper) that contains the code that's been extracted from `blocking`. It doesn't contain any of the other locking primitives, since those have since been moved into other crates.

It still needs to be cleaned up a little bit, but once it is we can hopefully just upload it onto `crates.io` to replace the old version of `piper`.

**Comment by fogti** [comment]
Do there any benchmarks exist against non-blocking use of native OS pipes?

**Comment by notgull** [comment]
I wrote some benchmarks. It looks like the pipe is around 5 times as fast as a Unix pipe and around 50 times as fast as a naive TCP pipe.

![image](https://user-images.githubusercontent.com/19805233/230737456-a7c03df4-76bb-48ad-a8e7-6bd66252acce.png)

**Comment by notgull** [comment]
@smol-rs/admins Are there any objections to me taking the `piper` crate above, moving it into the `smol-rs` organization, and publishing it as `piper` version 0.2.0?

**Comment by zeenix** [comment]
> @smol-rs/admins Are there any objections to me taking the `piper` crate above, moving it into the `smol-rs` organization, and publishing it as `piper` version 0.2.0?

Nice work as always. I've no objections.

**Comment by notgull** [comment]
Great! I've published `piper` v0.2.0.
