### ISSUE TITLE
Overflow mode

### ISSUE THREAD

**Issue by alandiwix** [smol-rs/async-channel#44]
Would it be possible to have overflow mode (similar to one in async_broadcast) in this implementation? Would be nice to have this mode for a channel that doesn't require Clone for messages.

**Comment by zjijz** [comment]
I also have a use case where I want a async SPSC bounded channel that follows the overflow method of `async-broadcast` when the channel is filled instead of blocking new sends. I was thinking something that would be inherent to the channel itself, so adding a creation function like `async_channel::bounded_circular` instead of a mutable overflow mode set.

I can use `async-broadcast` for my case as well so I'm not blocked.

**Comment by taiki-e** [comment]
This should be relatively easy to do after adding a function similar to https://github.com/crossbeam-rs/crossbeam/commit/bd75c3c45edb78a731956c01458b75e5b69a8146 to [concurrent-queue](https://github.com/smol-rs/concurrent-queue).

**Comment by notgull** [comment]
This function has been added to `concurrent-queue`. Once it's released we can implement this functionality.
