### ISSUE TITLE
Async-channel 2.3.0 fails to compile with concurrent-queue below 2.5.0

### ISSUE THREAD

**Issue by creberust** [smol-rs/async-channel#92]
Hi,

The selected version of `concurrent-queue` is incorrect in the `Cargo.toml` and should be at least `2.5` since #89 .

`async-channel` version 2.3.0 use `ForcePushError` which is only available since `concurrent-queue` version 2.5.0.

Thus, if you have any version prior to 2.5.0 in your `Cargo.lock`, it will not compile. (This actually fails only if you have a version of `concurrent-queue` previously set to `2.4.0`, the others versions are not compatible with `event-listener`, which is used by `concurrent-queue`).

Simple steps to reproduce the error:

```bash
cargo new ac-bug
cd ac-bug

cargo add async-channel@2.3.0

# Everything works fine because `cargo` will pull the last version of `concurrent-queue` with 2.x.y.
cargo b

# This is valid because `concurrent-queue` should be `^2.4.0` thanks to `event-listener`.
cargo update concurrent-queue --precise 2.4.0 

# Note: This will be rejected
cargo update concurrent-queue --precise 2.3.0
 
# Kaboom
cargo b
```

**Comment by AucaCoyan** [comment]
Hi! Thanks for resolving it 😊

Sadly, I'm hitting the version 2.3.0 because of some logic of cargo that I cannot understand 😢 .

Are you able to yank the 2.3.0 release? so cargo can't pick that version for whatever reason it might be able to.
Thanks! 🙏🏼

**Comment by taiki-e** [comment]
@AucaCoyan

Yanking just for minimal-versions may cause problems, so it will not be done (see https://github.com/smol-rs/async-lock/issues/98#issuecomment-2769974302 and linked issue for details). And please note that yanking is not magic. If for some reason you cannot change async-channel from 2.3.0, yanking 2.3.0 may result in a version resolution failure instead of fixing the problem.

Please update your version of concurrent-queue as described in this issue if for some reason you need to keep async-channel pinned at 2.3.0.

**Comment by AucaCoyan** [comment]
I understand. Thank you for the explanation!
